### ISSUE TITLE
Toubleshooting with build on npm

### ISSUE THREAD

**Issue by vladcorn** [BEE-Plugin/Bee-plugin-official#30]
Please check build log

**Comment by yuliia-liaison** [comment]
The same, `error TS2307: Cannot find module '@mailupinc/bee-plugin'`

**Comment by dzinhtoan** [comment]
Same issue:
`Cannot find module '@mailupinc/bee-plugin' or its corresponding type declarations.ts(2307)
`

**Comment by vladcorn** [comment]
the builded package is pure, only license, package.json and readme

**Comment by Silassiai** [comment]
Is this one fixed already?
![image](https://user-images.githubusercontent.com/18419961/132344108-4e13b050-501c-466c-b136-c0cd2ab7dc88.png)

**Comment by rmehta-daxko** [comment]
This is what we are getting https://registry.npmjs.org/@mailupinc/bee-plugin/-/bee-plugin-1.3.7.tgz, package missing the dist folder

Please fix asap.

**Comment by gjsyme** [comment]
1.3.7 gives me the same error as @yuliia-liaison but I was able to get my code to compile using (exact version) 1.3.6

**Comment by shayantabaei** [comment]
I'm also experiencing this issue:

[12:38:27]Browserslist: caniuse-lite is outdated. Please run:
[12:38:27]npx browserslist@latest --update-db
[12:38:27]
[12:38:27]Why you should do it regularly:
[12:38:27]https://github.com/browserslist/browserslist#browsers-data-updating
[12:38:55]Failed to compile.
[12:38:55]
[12:38:55]./src/common/components/bee-free-editor/BeeFreeEditor.tsx
[12:38:55]Cannot find module: '@mailupinc/bee-plugin'. Make sure this package is installed.
[12:38:55]
[12:38:55]You can install this package by running: yarn add @mailupinc/bee-plugin.

This has appeared in my build logs in the last 4 days

**Comment by vladcorn** [comment]
trouble is fixed
